[build]
target-dir = "~/.cargo/target"

[profile.release]
codegen-units = 1 # Allows compiler to perform better optimization.
lto = true        # Enables Link-time Optimization.
opt-level = 3     # Use 3 to optimize performance, z to optimize for size, and s for something in-between
strip = true      # Ensures debug symbols are removed.

